### PR TITLE
4219 Inflation: combine special calculation domains into one under the name acs

### PR DESCRIPTION
**Pull request by SPTKL**
### Summary
   - What was wrong?
      - variables in prev year (2006-2010) that should be inflated were not actually inflated
   - What is the fix?
      - combining the acs related special calculation rules into one 
   - Why?
     > moving backwards here
      - `demographic` was passed as the default domain. It was a place holder? since we moved from 4 separate tables based on each domain in favor of combined tables based on year (`acs."year"`), the concept of domain is less relevant.
      https://github.com/NYCPlanning/labs-factfinder-api/blob/b4f92bc0d8fee3e48c1fb6eec05cafebf0bf4ac2/routes/profile.js#L61-L65
     - profileName was then passed into DataProcessor
     https://github.com/NYCPlanning/labs-factfinder-api/blob/b4f92bc0d8fee3e48c1fb6eec05cafebf0bf4ac2/routes/profile.js#L99-L101
    - Which is then used to look up special calculation rules specific to that domain (economic, social, demographic, housing)
    https://github.com/NYCPlanning/labs-factfinder-api/blob/b4f92bc0d8fee3e48c1fb6eec05cafebf0bf4ac2/utils/data-processor.js#L42
    - Since the default is `demographic`, there's no special calculation rules retrieved when calculating a special variable from any other domains. 
    - so we want to change the concept of `profiles`
       - from `decennial`, `economic`, `social`, `demographic`, `housing`
       - to `decennial`, `acs`

#### Tasks/Bug Numbers
 - Fixes [AB#4219](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/4219)
- Related to/Fixes [AB#4215](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4215) [AB#4218](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4218)

### Any other info you think would help a reviewer understand this PR?
- Just FYI the following TODO will need to be addressed for the numbers to be calculated correctly
https://github.com/NYCPlanning/labs-factfinder-api/blob/b4f92bc0d8fee3e48c1fb6eec05cafebf0bf4ac2/routes/profile.js#L61

- Also the inflation factor is out of date, we would need to update it
https://github.com/NYCPlanning/labs-factfinder-api/blob/b4f92bc0d8fee3e48c1fb6eec05cafebf0bf4ac2/special-calculations/data/constants.js#L2

### CODE REVIEW

**Comment by SPTKL** [comment]
@EricaMaurer confirming the new inflation factor is 1.1751
> based on this commit message https://github.com/NYCPlanning/db-acs-2020/commit/80d57b020477cd6efdbc9e4e1c7f9cb7db955a90

**Comment by godfreyyeung** [comment]
Currently the code still has some dependencies on the way that the special-calculations object is broken out into different domains. My thought it that we need to first combine all those domain sections under thet `special-calculations/` folder into one file (object), and update those sections of code so that we no longer need to know the domain to access the appropriate special variables. See `routes/profile.js` line 109 

image

**Comment by SPTKL** [comment]
@godfreyyeung  the only thing to be careful is that we still want to separate acs and decennial, because there are cases where acs / decennial share variable names, but different methodology. I can walk you through this if you have time

**Comment by godfreyyeung** [comment]
Yes let's meet today

**Comment by TylerMatteo** [comment]
Is this PR still needed? It looks like some of it would be covered by https://github.com/NYCPlanning/labs-factfinder-api/pull/130.

**Comment by SPTKL** [comment]
you would still need to change the inflation factor
image

**Comment by SPTKL** [comment]
closing, this is already implemented
#130

**Pull request closed without merging**
